sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_8a9991dd5b46_key -iv $encrypted_8a9991dd5b46_iv -in inbound-vim-308008-dff9ce6bdc5b.json.enc -out inbound-vim-308008-dff9ce6bdc5b.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file inbound-vim-308008-dff9ce6bdc5b.json
  - gcloud config set project inbound-vim-308008
  - gcloud config set compute/zone europe-west3-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stephengrider/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
